title: Support! International
email: info@supportlearning.org
description: >
  Founded in 2014, Support! International is a global youth-led education NGO dedicated
  to bringing innovative educational programmes to different communities in need. Since
  our founding, we have grown from 1 site and 1 programme to 6 sites operating 9 programmes,
  each initiated, led and maintained by passionate, driven and caring young leaders.
  Our mission has continually been to create opportunities and foster connections for
  individuals from all backgrounds within communities, under the guiding principle and
  firm belief that young people are tomorrow’s leaders.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.supportlearning.org" # the base hostname & protocol for your site
# url: "http://127.0.0.1:4000"
twitter_username: support
facebook_username: supportintlfoundation
paginate: 54

# Build settings
markdown: kramdown
